name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call: {}

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - name: Install dependencies
        run: bun install

      - name: Run Format
        run: bun run format

      - name: Run Lint
        run: bun run lint

      - name: Run Tests
        run: bun test
